laba10/todoapp_django/Todoproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from todolist import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todolists/', include('todolist.urls')),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'), #Ссылки для входа, выхода и регистрации 
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),

]

laba10/todoapp_django/todolist/urls.py
from django.conf.urls import url
from . import views

app_name = 'todolist'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.CreateTodolist.as_view(), name='create_todolist'),
    url(r'^(?P<list_id>[0-9]+)/$', views.ListDetail.as_view(), name='list-detail'),
    url(r'^(?P<list_id>[0-9]+)/update/$', views.ListDetailUpdate.as_view(), name='update_todolist'),  #Добавили отдельные ссылки для каждого действия
    url(r'^(?P<list_id>[0-9]+)/delete/$', views.ListDetailDelete.as_view(), name='list-detail-delete'),
    url(r'^(?P<list_id>[0-9]+)/create/$', views.TaskCreate.as_view(), name='create_task'),
    url(r'^(?P<list_id>[0-9]+)/tasks/(?P<pk>[0-9]+)/$', views.TaskDetail.as_view(), name='task-detail'),
    url(r'^(?P<list_id>[0-9]+)/tasks/(?P<pk>[0-9]+)/update/$', views.TaskUpdate.as_view(), name='task-detail-update'),
    url(r'^(?P<list_id>[0-9]+)/tasks/(?P<pk>[0-9]+)/delete/$', views.TaskDetailDelete.as_view(), name='task-detail-delete'),
]

laba10/todoapp_django/todolist/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)
    is_active = models.BooleanField(default=False)
    confirmation_token = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.username

laba10/todoapp_django/todolist/forms.py
from django import forms
from todolist.models import User
import datetime

class TodolistCreateForm(forms.Form):
    name = forms.CharField(label='Todo list\'s name', max_length=50) # добавить кавычку после list's

class TodolistUpdateForm(forms.Form):
    name = forms.CharField(label='Todo list\'s name', max_length=50)

class LoginForm(forms.Form): #Из чего будет состоять 
    username = forms.CharField(label='username', max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())


class TaskCreateForm(forms.Form):
    name = forms.CharField(label = 'Task name', max_length=50)
    description = forms.CharField(widget=forms.Textarea, max_length=1000, label='Description')
    completed = forms.BooleanField(required=False)
    date_created = forms.DateField(initial=datetime.date.today)
    due_date = forms.DateField()
    PRIORITY = (
        ('h', 'High'),
        ('m', 'Medium'),
        ('l', 'Low'),
        ('n', 'None')
    )
    priority = forms.ChoiceField(choices=PRIORITY, label="Priority", initial='m', widget=forms.Select(), required=True)
    tags = forms.CharField(label = "Tags", max_length=100, required=False)

laba10/todoapp_django/todolist/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic, View
import requests
from django.http import HttpResponseRedirect
from .forms import TodolistCreateForm, LoginForm, TodolistUpdateForm, TaskCreateForm
from .services import create_auth_header, convert_from_json_to_obj
from .services import generate_confirmation_token
# Create your views here.

def index(request): #Как будет выглядеть главная страница 
    headers = create_auth_header(request.session)
    r = requests.get('http://127.0.0.1:8080/todolists/', headers=headers) #Обращаемся на сервер 
    todolists = r.json()
    return render(request, 'index.html', {'todolists': todolists, 'session': request.session})

class CreateTodolist(View):
    def get(self, request, *args, **kwargs):
        form = TodolistCreateForm()
        return render(request, 'create_todolist.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TodolistCreateForm(request.POST)
        if form.is_valid():
            post_data = {'name': form.cleaned_data['name']}
            headers = create_auth_header(request.session)
            response = requests.post('http://127.0.0.1:8080/todolists/', data=post_data, headers=headers)
            return HttpResponseRedirect('/todolists/')

class ListDetail(View):
    def get(self, request, list_id, *args, **kwargs):
        headers = create_auth_header(request.session)
        r = requests.get('http://127.0.0.1:8080/todolists/{}/'.format(list_id), headers=headers)
        list_details = r.json()
        return render(request, 'list_detail.html', {'list_details': list_details})

class ListDetailDelete(View):
    def get(self, request, list_id, *args, **kwargs):
        headers = create_auth_header(request.session)
        r = requests.delete('http://127.0.0.1:8080/todolists/{}/'.format(list_id), headers=headers)
        return redirect('todolist:index')

class ListDetailUpdate(View):
    def get(self, request, list_id, *args, **kwargs):
        form = TodolistUpdateForm()
        return render(request, 'update_todolist.html', {'form': form, 'list_id': list_id})
    def post(self, request, list_id, *args, **kwargs):
        form = TodolistUpdateForm(request.POST)
        if form.is_valid():
            post_data = {'name': form.cleaned_data['name']}
            headers = create_auth_header(request.session)
            r = requests.put('http://127.0.0.1:8080/todolists/{}/'.format(list_id), headers=headers, data=post_data)
            return redirect('todolist:index')

class TaskCreate(View):
    def get(self, request, list_id, *args, **kwargs):
        form = TaskCreateForm()
        return render(request, 'create_task.html', {'form': form, 'list_id': list_id})
    def post(self, request, list_id, *args, **kwargs):
        form = TaskCreateForm(request.POST)
        if form.is_valid():
            post_data = {'name': form.cleaned_data['name'], 'description': form.cleaned_data['description'],
                         'completed': form.cleaned_data['completed'], 'due_date': form.cleaned_data['due_date'],
                         'date_created': form.cleaned_data['date_created'], 'priority': form.cleaned_data['priority'],
                         'tags': form.cleaned_data['tags']}
            headers = create_auth_header(request.session)
            r = requests.post('http://127.0.0.1:8080/todolists/{}/tasks/'.format(list_id), data=post_data, headers=headers)
            return redirect('todolist:list-detail', list_id=list_id)


class TaskUpdate(View):
    def get(self, request, list_id, pk, *args, **kwargs):
        headers = create_auth_header(request.session)
        r = requests.get('http://127.0.0.1:8080/todolists/{}/tasks/{}/'.format(list_id, pk), headers=headers)
        form = TaskCreateForm(r.json())
        return render(request, 'update_task.html', {'form': form, 'list_id': list_id, 'pk': pk})
    def post(self, request, list_id, pk, *args, **kwargs):
        form = TaskCreateForm(request.POST)
        if form.is_valid():
            post_data = {'name': form.cleaned_data['name'], 'description': form.cleaned_data['description'],
                         'completed': form.cleaned_data['completed'], 'due_date': form.cleaned_data['due_date'],
                         'date_created': form.cleaned_data['date_created'], 'priority': form.cleaned_data['priority'],
                         'tags': form.cleaned_data['tags']}
            headers = create_auth_header(request.session)
            r = requests.put('http://127.0.0.1:8080/todolists/{}/tasks/{}/'.format(list_id, pk), headers=headers, data=post_data)
            return redirect('todolist:list-detail', list_id=list_id)


class TaskDetail(View):
    def get(self, request, list_id, pk, *args, **kwargs):
        headers = create_auth_header(request.session)
        r = requests.get('http://127.0.0.1:8080/todolists/{}/tasks/{}/'.format(list_id, pk), headers=headers)
        task_details = r.json()
        return render(request, 'task_detail.html', {'task_details': task_details, 'list_id': list_id})

class TaskDetailDelete(View):
    def get(self, request, list_id, pk, *args, **kwargs):
        headers = create_auth_header(request.session)
        r = requests.delete('http://127.0.0.1:8080/todolists/{}/tasks/{}/'.format(list_id, pk), headers=headers)
        return redirect('todolist:list-detail', list_id=list_id)

class LoginView(View):
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            post_data = {'username': form.cleaned_data['username'], 'password': form.cleaned_data['password']}
            response = requests.post('http://127.0.0.1:8080/api-token-auth/', data=post_data)
            credentials = response.json()
            if credentials.get('token', False):
                request.session['token'] = credentials['token']
                print('token in session')
                print(request.session['token'])
                return HttpResponseRedirect("/todolists/")
            else:
                print('not found token')
                return HttpResponse("You email/password is wrong!", status=403)

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        request.session.flush()
        return HttpResponseRedirect('/todolists/')

from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth

class RegisterView(View):
    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})
    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            post_data = {'username': form.cleaned_data['username'], 'password': form.cleaned_data['password2']}
            response = requests.post('http://127.0.0.1:8080/users/', data=post_data)
            return HttpResponseRedirect('/login')

laba10/todoapp_django/todolist/templates/create_task.html
<a href="{% url 'todolist:list-detail' list_id=list_id %}">Вернуться к списку задач</a>
<form action="{% url 'todolist:create_task' list_id=list_id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

laba10/todoapp_django/todolist/templates/create_todolist.html
<form action="{% url 'todolist:create_todolist' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

laba10/todoapp_django/todolist/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todolists</title>
</head>
<body>
    <h1>Todolists</h1>
    {% if not todolists.detail %}
    <ul>
        {% for todolist in todolists %}
            <li>
                name: <a href="/todolists/{{ todolist.id }}/">{{ todolist.name }}</a>
                <a href="/todolists/{{ todolist.id }}/delete/">delete</a>
                <a href="/todolists/{{ todolist.id }}/update/">update</a>
{#       not necessary         <div>owner: {{ todolist.owner }}</div>#}
            </li>
        {% endfor %}
    </ul>
    {% elif todolists.detail %}
        <p>{{ todolists.detail }}</p>
    {% endif %}
    <a href="{% url 'todolist:create_todolist' %}">Create new</a> 
    <a href="{% url 'register' %}">Registration</a>
    {% if not session.token %}
        <a href="{% url 'login' %}">Login</a>
    {% else %}
        <a href="{% url 'logout' %}">Logout</a>
    {% endif %}
</body>
</html>

laba10/todoapp_django/todolist/templates/list_detail.html
<a href="{% url 'todolist:index' %}">На главную</a>
<h1>List details of: {{ list_details.name }}</h1>
<p>ID: {{ list_details.id }}</p>
<p>Владелец: {{ list_details.owner }}</p>
<p>Таски:
    {% for task in list_details.tasks %}
        <a href="/todolists/{{ list_details.id }}/tasks/{{ task }}">{{ task }}</a>
    {% endfor %}
</p>
<a href="{% url 'todolist:create_task' list_id=list_details.id %}">Добавить новый таск</a>

laba10/todoapp_django/todolist/templates/login.html
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log in!">
</form>

laba10/todoapp_django/todolist/templates/register.html
<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registration">
</form>
  

laba10/todoapp_django/todolist/templates/shared_tasks.html
<h1>С вами поделились задачами:</h1>
{% for task in tasks %}
    {% for key, value in task.items %}
        <p>{{ key }} – {{ value }}</p>
    {% endfor %}
{% endfor %}

laba10/todoapp_django/todolist/templates/task_detail.html
<a href="{% url 'todolist:list-detail' list_id=list_id %}">Перейти к такслисту</a>
<h1>Details of {{ task_details.name }}</h1>
{% for key, value in task_details.items %}
<p>{{ key }} – {{ value }}</p>
{% endfor %}
<a href="/todolists/{{ task_details.tasklist }}/tasks/{{ task_details.id }}/delete/">Удалить этот task</a>
<a href="{% url 'todolist:task-detail-update' list_id=list_id pk=task_details.id %}">Обновить этот task</a>

laba10/todoapp_django/todolist/templates/update_task.html
<a href="{% url 'todolist:list-detail' list_id=list_id %}">Вернуться к списку задач</a>
<form action="{% url 'todolist:task-detail-update' list_id=list_id pk=pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

laba10/todoapp_django/todolist/templates/update_todolist.html
<form action="{% url 'todolist:update_todolist' list_id=list_id %}" method="post">
    {% csrf_token %}
    <h1>Updating todolist #{{ list_id }}</h1>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>